#!/bin/sh

cd "${0%/*}" || exit
#------------------------------------------------------------------------------

wclean compressible
wclean incompressible

rm -f foamVersionThisIsCompiledFor

#------------------------------------------------------------------------------
